[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
cache_path  = 'cache_forge'

solc_version='0.8.22'
evm_version='paris'
optimizer = true
optimizer_runs = 9999

remappings = [
    "@contracts/=contracts/",
	'forge-deploy/=node_modules/forge-deploy/contracts',
]

# forge-dpeloy
fs_permissions = [
	{ access = "read-write", path = "./deployments"},
	{ access = "read", path = "./out"}
]