name: ci

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup Environment
      uses: ./.github/actions/setup-environment

    - name: Run foundry build
      run: |
        forge --version
        forge build
      id: build

  lint-check:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v4

    - name: Setup Environment
      uses: ./.github/actions/setup-environment

    - name: Run foundry fmt check
      run: |
        forge fmt --check
      id: fmt

  test:
    runs-on: ubuntu-latest
    needs: lint-check
    steps:
    - uses: actions/checkout@v4

    - name: Setup Environment
      uses: ./.github/actions/setup-environment
      
    - name: Run foundry tests
      # --ast tests enables inline configs to work https://github.com/foundry-rs/foundry/issues/7310#issuecomment-1978088200
      run: |
        forge test -vvv --gas-report --ast 
      id: test
